FROM python:3.13-slim

WORKDIR /app

COPY requirements-dashboard.txt .

RUN python -m pip install \
    --no-cache-dir \
    -r requirements-dashboard.txt

COPY dashboard.py .
COPY database.py .
COPY dashboard_controller.py .

COPY templates ./templates
COPY static ./static

EXPOSE 5000

CMD ["python", "dashboard.py"]